### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by 583** [free-gx/cf-agent#1]
sh-3.2# cf-agent proxy
proxy running...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Socket.onerror (_stream_readable.js:733:7)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by tututu-patch** [comment]
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Socket.onerror (_stream_readable.js:737:7)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:74:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by kxmp** [comment]
I have this problem too.
It looks **only** happen when you query https url

**Comment by Initial-heart-1** [comment]
So, do you have any idea? I have the same problem T_ T

**Comment by free-gx** [comment]
> I have this problem too. It looks **only** happen when you query https url I sniffed the traffic and found that client don't even sent tls-handshake and just crashed!!

这应该是你的网络被sni 阻断，当初开启tls1.3可以启用esni，而esni现在已经无法使用，所以需要绑定个人域名
